[package]
name = "day13pt1"
version = "0.1.0"
authors = ["HeadBeeGuy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.9.1"
